from django.urls import include, path

from . import views

urlpatterns = [
    path('api/', include('restaurant.api_urls')),
    path('login/', views.SiteLoginView.as_view(), name='login'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('logout/', views.SiteLogoutView.as_view(), name='logout'),
    path('', views.InformationView.as_view(), name='information'),
    path('products/', views.MenuItemListView.as_view(), name='products'),
    path('products/<int:pk>/', views.MenuItemDetailView.as_view(), name='product_detail'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('data/', views.DataIndexView.as_view(), name='data_index'),
    path('data/users/', views.UserListView.as_view(), name='user_list'),
    path('data/users/<int:pk>/', views.UserDetailView.as_view(), name='user_detail'),
    path('data/users/create/', views.UserCreateView.as_view(), name='user_create'),
    path('data/users/<int:pk>/update/', views.UserUpdateView.as_view(), name='user_update'),
    path('data/users/<int:pk>/delete/', views.UserDeleteView.as_view(), name='user_delete'),
    path('data/categories/', views.CategoryListView.as_view(), name='category_list'),
    path('data/categories/<int:pk>/', views.CategoryDetailView.as_view(), name='category_detail'),
    path('data/categories/create/', views.CategoryCreateView.as_view(), name='category_create'),
    path('data/categories/<int:pk>/update/', views.CategoryUpdateView.as_view(), name='category_update'),
    path('data/categories/<int:pk>/delete/', views.CategoryDeleteView.as_view(), name='category_delete'),
    path('data/menu-items/', views.MenuItemDataListView.as_view(), name='menu_item_data_list'),
    path('data/menu-items/<int:pk>/', views.MenuItemDataDetailView.as_view(), name='menu_item_data_detail'),
    path('data/menu-items/create/', views.MenuItemCreateView.as_view(), name='menu_item_create'),
    path('data/menu-items/<int:pk>/update/', views.MenuItemUpdateView.as_view(), name='menu_item_update'),
    path('data/menu-items/<int:pk>/delete/', views.MenuItemDeleteView.as_view(), name='menu_item_delete'),
    path('data/orders/', views.OrderListView.as_view(), name='order_list'),
    path('data/orders/<int:pk>/', views.OrderDetailView.as_view(), name='order_detail'),
    path('data/orders/create/', views.OrderCreateView.as_view(), name='order_create'),
    path('data/orders/<int:pk>/update/', views.OrderUpdateView.as_view(), name='order_update'),
    path('data/orders/<int:pk>/delete/', views.OrderDeleteView.as_view(), name='order_delete'),
    path('data/order-items/', views.OrderItemListView.as_view(), name='order_item_list'),
    path('data/order-items/<int:pk>/', views.OrderItemDetailView.as_view(), name='order_item_detail'),
    path('data/order-items/create/', views.OrderItemCreateView.as_view(), name='order_item_create'),
    path('data/order-items/<int:pk>/update/', views.OrderItemUpdateView.as_view(), name='order_item_update'),
    path('data/order-items/<int:pk>/delete/', views.OrderItemDeleteView.as_view(), name='order_item_delete'),
    path('data/payments/', views.PaymentListView.as_view(), name='payment_list'),
    path('data/payments/<int:pk>/', views.PaymentDetailView.as_view(), name='payment_detail'),
    path('data/payments/create/', views.PaymentCreateView.as_view(), name='payment_create'),
    path('data/payments/<int:pk>/update/', views.PaymentUpdateView.as_view(), name='payment_update'),
    path('data/payments/<int:pk>/delete/', views.PaymentDeleteView.as_view(), name='payment_delete'),
    path('data/favorites/', views.FavoriteListView.as_view(), name='favorite_list'),
    path('data/favorites/<int:pk>/', views.FavoriteDetailView.as_view(), name='favorite_detail'),
    path('data/favorites/create/', views.FavoriteCreateView.as_view(), name='favorite_create'),
    path('data/favorites/<int:pk>/update/', views.FavoriteUpdateView.as_view(), name='favorite_update'),
    path('data/favorites/<int:pk>/delete/', views.FavoriteDeleteView.as_view(), name='favorite_delete'),
    path('data/reviews/', views.ReviewListView.as_view(), name='review_list'),
    path('data/reviews/<int:pk>/', views.ReviewDetailView.as_view(), name='review_detail'),
    path('data/reviews/create/', views.ReviewCreateView.as_view(), name='review_create'),
    path('data/reviews/<int:pk>/update/', views.ReviewUpdateView.as_view(), name='review_update'),
    path('data/reviews/<int:pk>/delete/', views.ReviewDeleteView.as_view(), name='review_delete'),
]
