# Generated by Django 6.0.5 on 2026-05-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menuitem_image_alter_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='composition',
            field=models.TextField(blank=True, verbose_name='Состав'),
        ),
    ]
