# Generated by Django 6.0.5 on 2026-05-26 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_remove_order_address_remove_reservation_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='description',
        ),
    ]
